DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USER_MESSAGES;
 
CREATE TABLE USERS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  EMAIL VARCHAR(250) DEFAULT NULL,
  MOBILE_NUMBER VARCHAR(250) NOT NULL,
  SUBSCRIBED_TO_SCORE_ALERT BOOLEAN DEFAULT FALSE
);

CREATE TABLE USER_MESSAGES (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    USER_ID INT NOT NULL,
    RECEIVED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MESSAGE VARCHAR(250) NOT NULL
);